### PR TITLE
Update used frameworks plus Redesign UI

### PR DESCRIPTION
**Pull request by janrenz**
Updated:
- Bootstrap
- Rails
- Works with ruby 2
- Major UI Redesign

You might want to check this and cherrypick. We could also meetup in Berlin!

### CODE REVIEW

**Comment by janrenz** [comment]
HI, i guess this is quite ok now. I found some issue with the can_edit _account method, that still need to be fixed.

**Comment by tkadauke** [comment]
Thanks for all these additions! I will take a look at it after work tonight :-)

**Comment by tkadauke** [comment]
I'm looking at your changes right now and I have to say I love the design!

**Comment by janrenz** [comment]
Design Template props to these guys: https://github.com/almasaeed2010/AdminLTE

**Comment by tkadauke** [comment]
I have cleaned up your pull request, squashed it into one commit and added it to the new rails4 branch. I removed a couple of things that you should probably .gitignore, like all of the project files. Also the phantomjs binary does not belong in the git repository since it's not portable. Other than that, great pull request and thank you for your contribution! :-)

**Comment by janrenz** [comment]
One more note: The fixed ruby version in the gemfile can be removed. This is heroku / dokku only i guess.

**Comment by tkadauke** [comment]
Actually, RVM listens to that declaration, too and bundler raises an exception if the ruby version is incorrect. So I think it's the ideal solution :-)

**Comment by tkadauke** [comment]
I just deployed your redesign and Rails upgrade together with a couple of my own additions. I think it looks awesome. Thanks again for your contribution! :)

Oh yeah, I'd love to meet up and hack on Tinymon in Berlin.

**Pull request closed without merging**
