### PR TITLE
Add Test Step that looks for visible content only

### PR DESCRIPTION
**Pull request by janrenz**
With this addition you can search for either content within the html (using a regex) or through visible text in the rendered page.
Its also now possible to send out notifications on every check run.

This also includes some fixes for postgres migration.

### CODE REVIEW

**Comment by tkadauke** [comment]
Hey, sorry that I didn't look into this PR yet, I'm still working on moving the test suite over to rspec. I already finished ~4000 specs, and there are about 1000 more to go.

**Comment by janrenz** [comment]
HI,  what do you think of having some cold drinks and do some hacking this weekend?

**Comment by tkadauke** [comment]
I already have plans this weekend. How about next weekend?

**Comment by janrenz** [comment]
Sounds fine as well :-) I should be available at least one day.

**Pull request closed without merging**
